@startuml

left to right direction

actor "Visitante" as Visitor
actor "Administrador" as Admin

rectangle "Plataforma NovoLar" {

    usecase "Consultar catálogo de animais" as UC01
    usecase "Visualizar detalhes do animal" as UC02
    usecase "Registrar interesse em adoção" as UC03

    usecase "Autenticar-se" as UC04
    usecase "Gerenciar animais" as UC05
    usecase "Gerenciar solicitações de adoção" as UC06
    usecase "Visualizar dashboard" as UC07
}

Visitor --> UC01
Visitor --> UC02
Visitor --> UC03

Admin --> UC04
Admin --> UC05
Admin --> UC06
Admin --> UC07

@enduml